services:
  projectdb:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ProjectDb

    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_project:/var/lib/postgresql/data/


volumes:
  postgres_project: