name: Test and Deploy

env:
    RG: go-gin-group
    RG-LOCATION: northeurope
    TEMPLATE_FILE_PATH: cloud/main.bicep

on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]
        
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    Unit-Test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to Azure
              uses: azure/login@v2.3.0
              with:
                client-id: ${{ secrets.CLIENT_ID }}
                tenant-id: ${{ secrets.TENANT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            
            - name: Create resource group
              uses: azure/cli@v2.1.0
              with:
                inlineScript: |
                    az group create \
                    --resource-group ${{ env.RG }} \
                    --location ${{ env.RG-LOCATION }}

            - name: Validate Bicep template
              uses: azure/cli@v2.1.0
              with:
                inlineScript: |
                    az deployment group validate \
                    --resource-group ${{ env.RG }} \
                    --template-file "${{ env.TEMPLATE_FILE_PATH }}"
    
    Deploy:
      needs: Unit-Test
      runs-on: ubuntu-latest

      steps:
          - uses: actions/checkout@v4
          - name: Login to Azure
            uses: azure/login@v2.3.0
            with:
              client-id: ${{ secrets.CLIENT_ID }}
              tenant-id: ${{ secrets.TENANT_ID }}
              subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          - name: Deploy Ressources
            uses: azure/cli@v2.1.0
            with:
              inlineScript: |
                  az deployment group create \
                  --resource-group ${{ env.RG }} \
                  --template-file "${{ env.TEMPLATE_FILE_PATH }}"